# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('participants', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='user_ws_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=700)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('schedule', models.FileField(upload_to=website.models.upload_location)),
                ('instruct_part', models.TextField(max_length=1000)),
                ('instruct_coord', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='user_ws_dates',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Workshops'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Workshops'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book_slot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user_ws_dates'),
        ),
        migrations.AddField(
            model_name='book_slot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
