# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Slot',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='user_ws_dates',
            new_name='Slot',
        ),
        migrations.RenameModel(
            old_name='Workshops',
            new_name='Workshop',
        ),
    ]
